<a href="https://colab.research.google.com/github/nayem18/Machin-Learning-ML-python/blob/main/Matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[3, 2], [7, 4]])
B = np.array([[3, 7, 2], [9, 4, 7]])
AB = np.matmul(A, B)
print(A)
print(B)
print(AB)
print(AB.shape)

[[3 2]
 [7 4]]
[[3 7 2]
 [9 4 7]]
[[27 29 20]
 [57 65 42]]
(2, 3)
